### ISSUE TITLE
Large entity?

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/openDS#10]
Did I understand correctly that the OpenDS is trying to hold all the specimen related data in one entity? If so isn't there a high change that the entity will grow over time quite large?

**Comment by hardistyar** [comment]
A DS will hold mainly links to data, with sufficient other information to allow a system to determine whether to follow the link or not. That latter part is the tricky balancing act between having enough information to know that following and unpacking from the link is worthwhile, versus putting too much data in the DS with consequence that it grows unwieldy.

**Comment by vixriihi** [comment]
ok that sounds good. After reading the docs I got the picture that it (loans + specimen data + history of all that) was included in the DS itself, but I'll read through the docs again.

**Comment by hardistyar** [comment]
No, transactions and provenance (history) are stored separately and can be queried separately (or in conjunction).
