### ISSUE TITLE
Related project IGSN-- 

### ISSUE THREAD

**Issue by smrgeoinfo** [DiSSCo/openDS#14]
The objective of the IGSN e.V. is to implement and promote standard methods for identifying, citing, and locating physical samples with confidence by operating an international IGSN registration service.  https://www.igsn.org/
This activity has generated a model for basic cross domain sample (e.g. specimen) description  https://github.com/IGSN/metadata.
It has recently been funded to expand scope from earth science to include archeology and biology https://isamplesorg.github.io/home/

**Comment by sharifX** [comment]
Hi @smrgeoinfo, Thanks for your note, Yes, we are aware of IGSN and the new iSamples initiative. We had several brainstorming and technical meetings to understand how IGSN works and how it fits into our idea of Digital Specimen. We definitely learned a lot from IGSN implementation and business model. 

We are aware that wider global convergence and interoperability issues need to be discussed for sample and specimen related research. But at the moment, we are trying to address and understand some unique needs arising from natural science community where openDS work will guide the development of a [persistent identifier system for Digital Specimens](https://dissco.tech/2020/10/21/debunking-reliability-myths-for-pids-for-digital-specimens/).

**Comment by smrgeoinfo** [comment]
the 'persistent identifier system of Digital Specimens' link get this "Website blocked due to a suspicious top level domain (TLD)"

**Comment by hardistyar** [comment]
@smrgeoinfo if you're using something like Browser Guard you'll need to get Malwarebytes to whitelist the domain! https://forums.malwarebytes.com/topic/267508-blocked-due-to-a-suspicious-top-level-domain-tld/

**Comment by hardistyar** [comment]
If you're using a product like Malwarebytes Browser Guard, you'll need to contact them to get them to whitelist the domain.
See this example: https://forums.malwarebytes.com/topic/267508-blocked-due-to-a-suspicious-top-level-domain-tld/
