### ISSUE TITLE
ODS should import relevant DwC/ABCD terms for many of the basic properties

### ISSUE THREAD

**Issue by hardistyar** [DiSSCo/openDS#15]
[dwcobo](https://github.com/BiodiversityOntologies/dwcobo) offers "*OWL versions of the two DwC RDF files following OBO Foundry best practices and common methods. This will make it easier for anyone who wants to import DwC properties into their OBO ontology*" - as we want to do in ODS.

(Still in development. OBO Foundry purls for import not yet available/approved).

Note: Same conversion/import needs to be done for ABCD terms https://abcd.tdwg.org/terms/ from the namespace http://rs.tdwg.org/abcd/terms/...

Resolution of the issue is in part dependent on outcomes of TDWG alignment work on DwC and ABCD. Status/plans unknown at present time.

**Comment by sharifX** [comment]
closing old ticket. Check the new data model for the latest harmonisation.
