### ISSUE TITLE
ods:ID: change to lower case id

### ISSUE THREAD

**Issue by DavidFichtmueller** [DiSSCo/openDS#184]
### Term Name

ods:ID

### Digital Object Name

all of them

### Feedback

(This issue is only relevant when the proposed change in #152 is rejected.)

There are two contradicting naming rules/conventions that come to play here regarding the term name: properties should start with a lower case and abbreviations should be capitalized. We think the one regarding property names should weigh higher, as the other one is more for legibility purposes. The term ods:midsLevel also follows this line of thinking. Therefore we suggest to rename this property in all its uses to ods:id (if it is not replaced with dcterms:identifier).

**Comment by samleeflang** [comment]
This ticket has been superseded by the decision made in https://github.com/DiSSCo/openDS/issues/152
We will switch from `ods:ID` to either `dcterms:identifier` or `schema:identifier`.
I think it is safe to close this ticket, but feel free to open if you don't agree.
