### ISSUE TITLE
Example semantic description of _Elophila nymphaeata_ [NHMUK010517563]

### ISSUE THREAD

**Issue by hardistyar** [DiSSCo/openDS#19]
Copy and extend [example 2](https://github.com/DiSSCo/openDS/blob/master/json-examples-and-schemas/digital-specimen-object/basic-json-example2.md) to semantically describe butterfly _Elophila nymphaeata_ [NHMUK010517563](https://data.nhm.ac.uk/dataset/56e711e6-c847-4f99-915a-6894bb5c5dea/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/8966212). Add example semantics for label information such as collector and geography. JSON-LD representation.

**Comment by sharifX** [comment]
The [data model folder](https://github.com/DiSSCo/openDS/tree/master/data-model) has new examples based on the updated data model.
