### ISSUE TITLE
The Create Update Tombstone Event may not be generic enough

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/openDS#193]
### Suggestion

Capturing provenance data is an important part of openDS. I think we want to capture provenance for actions on the physical specimen, on the digital object and on the source system. The latter we do not yet support in this version of openDS. We handle provenance for the digital object a bit different from provenance on the physical object, where we record Activity based on prov-o on the digital object, but record Assertion for the physical object (based on GBIF UM and DwC). Maybe we should:
- align these a bit more, e.g. rename ods:Assertion to ods:Activity? the contents of these classes will be different though
- rework the Create Update Tombstone event object to allow for recording provenance of other activities on the Digital Object, in particular measurements.

**Comment by samleeflang** [comment]
Wouter we discussed this and everything you suggested should be covered by the CreateUpdateTombstone event and over provenance we have in effect. Would you agree to resolve this ticket?

**Comment by wouteraddink** [comment]
this ticket can be closed, we concluded that CreatUpdateTombstone event does not need a change and that an Assertion is capturing the result of an Activity rather than the Activity itself.
