### ISSUE TITLE
Ensure 1:1 relation between digital and physical specimen

### ISSUE THREAD

**Issue by huberrob** [DiSSCo/openDS#22]
Hi @hardistyar,

First, thanks for proposing this interesting concept! Maybe you can help me to understand how you make sure that a digital and its physical counterpart are permanently connected. I understand that 'A Digital Specimen has a one-to-one relation with a physical specimen ' as you state in the FAQs but I cannot see how you ensure this in the data model. 

I think this is somehow related to the concept of a digital representation of an instrument see: https://github.com/rdawg-pidinst where we have a yet unsolved discussion on how to link e.g. physical instruments with a digital record. See https://github.com/rdawg-pidinst/schema/issues/15

Robert

**Comment by hardistyar** [comment]
Hi @huberrob, I've made an explanation here: https://github.com/rdawg-pidinst/schema/issues/15#issuecomment-875519838. I hope it helps. If it raises new questions, please let me know.
