### ISSUE TITLE
Describing bird nest specimens, related eggs and anthropogenic materials found in the nest such as plastic water bottles.

### ISSUE THREAD

**Issue by smrgeoinfo** [DiSSCo/openDS#24]
see PR #23.  This issue is for discussion of solutions for the problem

**Comment by smrgeoinfo** [comment]
the anthropogenic materials are part of the birds nest.  For the 'materialType' property for the specimen, there are various 'plant fragments', 'anthropogenic materials', and maybe other stuff..  Options: include these as an array of values for materialType
"materialType":["plant fragments","plastic fragments", "animal hair"...]
or model with a hasPart relationship:
"objectType":"Bird nest",
"hasPart": [
  {"materialType":"plant fragment"}, {"materialType":"plastic fragment"}, {"materialType":"animal hair"}
]

**Comment by smrgeoinfo** [comment]
Eggs from the nest have some material type (depending on whether the embryo etc. is part of the specimen, or just a dried egg shell), and would be related to the nest specimen with a 'relatedResource' type link. I'm not clear on how such relationships are represented in the current schema, but an relationship object should include a URI for the target and a relationshipType that specifies the kind of relationship - e.g. for the eggs 'contained in' (as in eggs contained in nest).

**Comment by sharifX** [comment]
@smrgeoinfo Thanks for the comment. ```materialType``` with an array is definitely a better appoach. I will update the use case example. My json example was mostly for illustration purposes. 

I think the tricky aspect here is to align the standards development and data engineering work with different curation practices. We will need to get a better sense of how these anthropogenic materials are being curated and studied in relation with the specimen being studied (you can see the idea "Extended Specimen" here as well). I am guessing animal hair versus microplastics found in fish gut will have different curation and sampling lifecycle (some of the plastic materials might be thrown away). Often times some of these data are found in the "comments" or "condition" section and not published in the public portal. But I agree, ```materialType``` is a good starting point. 

Regarding relationships, there are different practices. For instance, this is the bird nest (https://bioportal.naturalis.nl/specimen/RMNH.AVES.175460.a) and the eggs (https://bioportal.naturalis.nl/specimen/RMNH.AVES.175460.b). You can see from the suffix that they are related but this is not machine readable FAIR metadata. ```relatedResource``` and ```relationshipType``` are good suggestions. ```contained in``` might be tricky -- after the collection, the eggs most likely be separated. Here we need some domain expertise and collection curation insight.
