### ISSUE TITLE
ID in JSON implementation

### ISSUE THREAD

**Issue by smrgeoinfo** [DiSSCo/openDS#26]
why not use @id for consistency with JSON ld for the node identifier?
e.g. (from digital-specimen-object/basic-json-example1.md):

```
{
  "@id": "https://handle.net/20.5000.1025/64ae0cf0dacb7bd20ba5",
  "$schema": "https://nsidr.org/schemas/opendsschema/20210222",
  "authoritative": { ....
```

**Comment by hardistyar** [comment]
@smrgeoinfo This is not a node identifier in the sense of an RDF graph but an identifier of a [FAIR Digital Object (FDO)](https://fairdo.org/), of which an open Digital Specimen (ods) is a kind.

If you look at [example-3 step 2 json](https://github.com/hardistyar/openDS/blob/json-schemas/json-examples-and-schemas/digital-specimen-object/basic-json-example3.md) (which I haven't merged yet) you can see this more clearly.

The `id` is the Handle for the object. The `@id` is the URI for a node in an RDF graph corresponding to this object. You will see that the path component of the URI corresponds to the identifier of the object i.e., the Handle, while the authority component (doi.org) is a proxy on the Web that provides a means for accessing the Handle resolution system to find the location of this object/resource.

Regardless of whether you use the `id` directly at the service access point of an object repository, or whether you use the `@id` on the Web, the same object will be given to you.

**Comment by smrgeoinfo** [comment]
I don't get the distinction between a FAIR Digital Object and a node in an RDF graph.   Doesn't the Digital object have an identifier that is supposed to be resolvable? Handles are just a flavor of identifier, are you thinking they're somehow different from URIs?  If the representation that is obtained by resolving id or @id the same, don't those identifier identify the same thing?

I'd be curious to know if anyone else in the community has thoughts about this, seems like the conversation was shut down pretty abruptly....

**Comment by hardistyar** [comment]
Happy to reopen the issue.

A FAIR Digital Object (FDO) can be a node in an RDF graph but doesn't have to be. The base definition of an FDO doesn't have this as a requirement or characteristic.

Handles are different from URIs, yes. Handles are simply identifiers of resources on a network, which do not contain any information about changeable attributes of the identified entity, such as its location or ownership. URIs, on the other hand do contain such information.

URIs that incorporate a Handle as in https://doi.org/<some handle> provide a specific mechanism for reaching the Handle resolution system from the World-Wide Web.

The Handle System is not part of the Web but part of the wider underlying Internet, just as (FAIR) digital objects have a span and applicability that is beyond the Web.

**Comment by smrgeoinfo** [comment]
lumping vs. splitting....

**Comment by sharifX** [comment]
closing this old as our FDO implementation and JSON schema have changed. check the [data model folder](https://github.com/DiSSCo/openDS/tree/master/data-model) for the latest schema.
