### ISSUE TITLE
collector name search and JSON implementation (people linkage)

### ISSUE THREAD

**Issue by infinite-dao** [DiSSCo/openDS#29]
Hej-hej,

I started commenting in https://github.com/DiSSCo/SDR/issues/27 but here is a more suitable place to ask.

I’m involved in [4.6 People Linkage](https://docs.google.com/document/d/1sNclNbnMJrIVWeV1-9Rikd3SUX00T2x3L5-Lwqcyx6A/edit#heading=h.afowc2vg1yb8) for collectors etc.. So far I managed to write a python wrapper to add a collector by a command like so (following the [SDR glalaxy workflow wrapper](https://github.com/DiSSCo/SDR/tree/main/galaxy-workflow)):

```bash
python 'main.py' -i ./test-data/open-ds-input.json -o ./test-data/open-ds-output.json --collector 'Linné'
```

As input/output I expect:

- input: a name tagged or specified or identified as collector
- output: add a list to JSON <abbr title="open Digital Specimen">openDS</abbr>

So far I contemplated and I came up with this:

```json
"original_collector_search": {
    "results": [
        {
            "item": {
                "type": "uri",
                "value": "http://www.wikidata.org/entity/Q1043"
            },
            "personLabel": {
                "xml:lang": "en",
                "type": "literal",
                "value": "Carl Linnaeus"
            },
            "personAltLabels": {
                "type": "literal",
                "value": "Carl Linn\u00e6us; Carl Nilsson Linn\u00e6us; Carl von Linnaeus; Carl von Linne; Carl von Linn\u00e9; Caroli Linn\u00e6i; Carolo Linnaeo; Carolo Linn\u00e6o; Carolus Linnaeus; Carolus Linn\u00e6us; Carolus a Linne; Carolus a Linn\u00e9; Karl von Linn\u00e9; L.; Linn.; Linnaeus; Linne; Linn\u00e6us; Linn\u00e9"
            },
            "genderLabel": {
                "xml:lang": "en",
                "type": "literal",
                "value": "male"
            },
            "dateOfBirth": {
                "datatype": "http://www.w3.org/2001/XMLSchema#dateTime",
                "type": "literal",
                "value": "1707-05-23T00:00:00Z"
            },
            "dateOfDeath": {
                "datatype": "http://www.w3.org/2001/XMLSchema#dateTime",
                "type": "literal",
                "value": "1778-01-10T00:00:00Z"
            },
            "image": {
                "type": "uri",
                "value": "http://commons.wikimedia.org/wiki/Special:FilePath/Carl%20von%20Linn%C3%A9.jpg"
            },
            "numApiOrdinal": {
                "datatype": "http://www.w3.org/2001/XMLSchema#int",
                "type": "literal",
                "value": "0"
            },
            "VIAF_ID_URI": {
                "type": "uri",
                "value": "http://viaf.org/viaf/34594730"
            },
            "ISNI_ID": {
                "type": "literal",
                "value": "0000 0001 2127 4957"
            },
            "WIKIDATA_ID_URI": {
                "type": "uri",
                "value": "http://www.wikidata.org/entity/Q1043"
            },
            "occupations": {
                "type": "literal",
                "value": "professor; ornithologist; bryologist; pteridologist; autobiographer; botanist; mycologist; entomologist; zoologist; geologist; biologist; naturalist; physician"
            },
            "occupationsWithLangPrefix": {
                "type": "literal",
                "value": "en:professor; en:ornithologist; en:bryologist; en:pteridologist; en:autobiographer; en:botanist; en:mycologist; en:entomologist; en:zoologist; en:geologist; en:biologist; en:naturalist; en:physician"
            }
        },
        {...},
        {...}
    ],
    "summary": "3 results searching collector \u201cLinne\u201d: Carl Linnaeus; Carl Linnaeus the Younger; Johan Stensson Rothman."
}
```

Ideas behind this:

- `summary` is *always* present
- `results` may be empty if nothing was found
- add as many meaningful properties as possible to let a human decide what collector matches best (`numApiOrdinal` may help: it’s the order of findings from the WikiBase Api (?the lower the value, the higher is the match?))
- the query works at first against WikiBase to get the people properties; the found wiki data ID could serve as a linkage to query further open linked data from other interfaces (e.g. BotanyPilot at BGBM or its extended version later on, because now its limited to herbarium sheets only)

Questions to clarify:

- How should the <abbr title="open Digital Specimen">openDS</abbr> list structure for collectors be constructed?
- What types of persons are to be tagged from <abbr title="optical recognition analysis">OCR</abbr>? 
  - original collector, secondary collector, collector manager, … ?
    - [specimen collector (OBI_0001895)](http://purl.obolibrary.org/obo/OBI_0001895): *«A person who collects the specimen»*—presumably the primary collector who took the being by hand at first
    - [specimen collector role (OBI_0001769)](http://purl.obolibrary.org/obo/OBI_0001769): *«An Investigation agent role borne by a person or organization which is realized in a specimen collection process.»*—presumably the persons involved in the collection process later on
    - [recorded by (Darwin Core term)](http://rs.tdwg.org/dwc/terms/recordedBy) as generic term definition: *«A list (concatenated and separated) of names of people, groups, or organizations responsible for recording the original Occurrence. The primary collector or observer, especially one who applies a personal identifier (recordNumber), should be listed first.»*
    - …
  - determiner, …
  - descriptor, …
  - other types ? Or is there already an ontology for person types to draw property names  from, and to use it here?

Thank you for any clarifications
Andreas

**Comment by infinite-dao** [comment]
Hej-hej,

I’m contemplating further if there are *multiple collectors*—one after another—to be searched and annotated through and it’s implementations in a JSON structure that may be meaningful. The [`dwc:recordedBy`](http://rs.tdwg.org/dwc/terms/recordedBy) is thematising it by pointing out in providing the primary collector *first* and *then* the others:
- [recorded by (Darwin Core term)](http://rs.tdwg.org/dwc/terms/recordedBy) definition: *«A list (concatenated and separated) of names of people, groups, or organizations responsible for recording the original Occurrence. The primary collector or observer, especially one who applies a personal identifier (recordNumber), should be listed first.»*

So the *later in time* a collector worked on a specimen, the further after in the collector name list he should be written, and I would separate them by semicolon, because there could be reversed names with comma, like “Linné, Carl” or so. Hence my proposal would be to think in list values (always), e.g.:

| Collector Search                        | In Command Line                                   | JSON part                                                                                         |
|-----------------------------------------|---------------------------------------------------|---------------------------------------------------------------------------------------------------|
| one: “Linné”                            | `--collector-list "Linné" `                       | `{"result_list": [0:[{1st}, {2nd}, {3rd}, …, {max.10}]]}`                                         |
| multiple: “Linné; Linnaeus the Younger” | `--collector-list "Linné; Linnaeus the Younger" ` | `{"result_list": [0:[{1st}, {2nd}, {3rd}, …, {max.10}], [1:[{1st}, {2nd}, {3rd}, …, {max.10}]]]}` |

… where 

1. `{1st}, {2nd}, {3rd}, …, {max.10}` means 
    - the *1<sup>st</sup> possibility* of a match, 
    - the *2<sup>nd</sup> possibility*, 
    - the *3<sup>rd</sup>* and up to maximal the *10<sup>th</sup> possibility* of a collector search match, and 
2. the zero-based index in `{"result_list": [0:[…], 1:[…]]}` indicates 
    - `0` is meant to be the *primary* collector
    - `1` is meant to be the *secondary* collector etc.

Does it make sense? Any objections or improvements?

Good bye, Andreas

**Comment by dshorthouse** [comment]
@infinite-dao Pleased to see that you're working on this. I suggest you visit with Sabine von Mering, Museum für Naturkunde if you haven't yet a chance to do so. That may be the quickest way to see & learn of others' work on this front. It touches on Attribution and so here's one place to see the other individuals involved https://www.tdwg.org/community/attribution/people/.

It's not clear to me if what you're looking for is:

1. clarity on how to structure search results,
2. how to structure objects about people that may aid in linking activities,
3. how to structure the link between person and object (what was their role & the activity they executed)

To be sure, there is some overlap between all these three needs but they are sufficiently different that a single structure (or sets of actionable tickets to do work) may not serve all three equally. However, if I understand what are your motivations, it seems to me that it's 2 above that is your primary driver. The first one gets you into issues of aliases, search patterns, etc. and the last one gets you into annotation space. Those are important, but less so than 2 for you at the moment. Correct?

So...what's the schema?

The Attribution group of folk have been working on an extension to DwC called "Agent Actions". It's long overdue & I'm the one who needs to give myself a kick. See https://github.com/tdwg/attribution/tree/master/people/dwc and the issues. Of course the schema does depend on what it is you want to do with it (i.e. 3 in your list) but if the business of making linkages to Person and specimen record are done elsewhere and the the openDS is merely the presentation of that effort, does your openDS schema about people need to store anything more than: `name`, `alternateName`, `verbatimName`, and an array of `identifiers`? And, leave it to whatever is behind those identifiers to store the (potentially contentious) demographical information.

**Comment by infinite-dao** [comment]
Thank you David (@dshorthouse) for directing me to useful standardised terms.

> It's not clear to me if what you're looking for is:
> 
> 1. clarity on how to structure search results,
> 2. how to structure objects about people that may aid in linking activities,
> 3. how to structure a link between person and object (what was their contextual role & the activity they performed) AND who is it that made the link

The [4.6. People Linkage](https://docs.google.com/document/d/1sNclNbnMJrIVWeV1-9Rikd3SUX00T2x3L5-Lwqcyx6A/edit#heading=h.afowc2vg1yb8) fixes on *“Output: URIs with reference to entity. Multiple entities will be supported, but no distinction made between roles.”*

So I want to provide a JSON scheme which makes sense by human reading and provides help for whatever decision later is made in the process (which is not my concern here right now), I’m concerned solely with providing automated (good) search results, so it regards mainly: *“1. clarity on how to structure search results”*

I will implement some remapping of my first proposal and I will post then again about a JSON search result structure.

**Comment by dshorthouse** [comment]
Thanks for clarifying the intent @infinite-dao. That helps focus on the deliverables. Should it be of use, here is the Elasticsearch "schema" I use for people in Bionomia, https://bionomia.net: https://github.com/bionomia/bionomia/blob/master/lib/elastic_user.rb#L13. And then the query used to display search results uses cross fields in a multi match in Elasticsearch: https://github.com/bionomia/bionomia/blob/master/helpers/query_helper.rb#L8 that weights parts of names and aliases to improve scores. This may help you work backwards to ascertain what are the necessary key/value pairs in the model to support such basic functionality like search or autocomplete to accommodate the vagaries of how human names may be expressed when family names and given names may be swapped (eg John Peter vs Peter John).

**Comment by infinite-dao** [comment]
Well @dshorthouse, now I become aware, that I do not have to invent the wheel twice ;-) perhaps. With your work on gathering person data of biological fields at https://bionomia.net I could just merge the results into the openDS herein and be done with it more or less. I’m reading into https://bionomia.net/developers and I …

- see the API `user.json` as JSON
  - provided by e.g. https://api.bionomia.net/user.json?limit=5&q=Carl+Linné which gets probably the most suitable data packages that we need, I’m inclined to use this, and I …
- see the the API with more deep analysis as JSON-LD
  - provided by e.g. https://api.bionomia.net/users/search?limit=5&q=Carl+Linné which I feel is perhaps to much data overload for the openDS itself but may serve for deep analysis OR …
  - I could just extract parts of it, e.g. `"dataFeedElement"`

As there could be more than one name to be searched for, the outer openDS could keep the same `{"result_list": [0:[…], 1:[…]]}` but inside there would be just (modified) binomia api results and that’s it. And as long as the searched persons are within the “world of natural history specimens” binomia seems a suitable gate to search through than to query wikidata manually.

I wonder, what IDs you plan to provide or if you want to keep it _simple_ and provide WikiData-ID and ORCID only?

**Comment by dshorthouse** [comment]
> I wonder, what IDs you plan to provide or if you want to keep it _simple_ and provide WikiData-ID and ORCID only?

It'll be purposefully simple because wikidata itself is a much better place to gather other identifiers and reconcile them against people entries. Keeping pace with wikidata, ORCID, and GBIF is hard enough.

I should say that there are consequences to the high-level decision in Bionomia that living people come from ORCID, deceased come from Wikidata. Living collectors/determiners/taxonomists who do not have an ORCID (but may have a wikidata entry) will not be in Bionomia & will not be in your search results. And, as this is a crowd-sourcing project of sorts, it is as complete or incomplete as we make it.

**Comment by infinite-dao** [comment]
Based on the thoughts of https://github.com/DiSSCo/openDS/issues/29#issuecomment-912400289, I managed to include name search of WikiData and Bionomia. The problem is, that both give back different terms, so I adjusted WikiData’s output to be similar like the one of Bionomia’s. In my version (as of October 6, 2021) the following term fields would be always given by default, i.e. in both query service results:

- `fullname`
- `livespan` (can be `null`)
- `thumbnail` (can be `null`)
- `description` (can be `null`)
- `identifiers`
- `score`
- and all other terms would be distinct to one of either query service

The results are thought of, as being always a nested list: for searching `Linné; Groom` it is thought as “Linné” being the 1st collector and “Groom” being here the 2nd collector etc.; in general:
```json
    "specimen_collector_search": {
        "results": {
            "wikidata": [ 
               [ {"1result1"}, {"1result2"} ], 
               [ {"2result1"} ] 
            ],
            "bionomia": [
               [ {"1result1"}, {"1result2"}, {"1result3"}, {"1result4"} ],
               [ {"2result1"}, {"2result2"} ]
            ]
        },
        "summary": [ 
          "1 all results’ summary",
          "2 all results’ summary"
        ]
    }
```
See an example for _one_ name search of “Groom”, so we get formally:

```json
        "results": {
            "wikidata": [ 
               [ {"1result1"} ] 
            ],
            "bionomia": [
               [ {"1result1"}, {"1result2"}, {"1result3"} ]
            ]
        },
        "summary": [ 
          "1 Bionomia result’s summary. 1 WikiData result’s summary."
        ]
```
… and in detail:
```json
    "specimen_collector_search": {
        "results": {
            "wikidata": [
                [
                    {
                        "id": "http://www.wikidata.org/entity/Q28913658",
                        "fullname": "Quentin Groom",
                        "givennames": "Quentin John",
                        "familyname": "Groom",
                        "alternateNames": "Q.J. Groom; Quentin J. Groom; Quentin John Groom",
                        "lifespan": "&#42; ?? month unknown 1965 &ndash; n.a.",
                        "thumbnail": null,
                        "description": "male: British botanist",
                        "occupations": "biodiversity informatician; botanist; researcher",
                        "numApiOrdinal": "0",
                        "score": "109",
                        "identifiers": "<https://isni.org/isni/0000000135211244> | <http://viaf.org/viaf/1273155105764076320004> | <http://www.wikidata.org/entity/Q28913658>"
                    }
                ]
            ],
            "bionomia": [
                [
                    {…},
                    {
                        "id": 58,
                        "score": 46.33884,
                        "orcid": "0000-0002-0596-5376",
                        "wikidata": null,
                        "fullname": "Quentin Groom",
                        "fullname_reverse": "Groom, Quentin",
                        "thumbnail": "https://bionomia.net/images/photo24X24.png",
                        "lifespan": null,
                        "description": "I'm interested in the use of computers to analyse and disseminate scientific ...",
                        "identifiers": "<https://orcid.org/0000-0002-0596-5376>"
                    },
                    {…}
                ]
            ]
        },
        "summary": [
            "Result 1 of Bionomia Search: 3 results searching person \u201cGroom\u201d as specimen collector: Percy Groom; Quentin Groom; Charles Ottley Groom Napier. Result 1 of Wikidata Search: One result searching person \u201cGroom\u201d as specimen collector: Quentin Groom."
        ]
    }
```

**Comment by sharifX** [comment]
Closing this old ticket. SDR has been finished and we have made some progress in the DiSSCo sandbox with ORCID integration. We can make use of bionomia API if needed. The annotation framework will provide options for the community to add wikidata items to the collector names.
