### ISSUE TITLE
Provenance datamodel

### ISSUE THREAD

**Issue by samleeflang** [DiSSCo/openDS#33]
Hi All,

I require some help with the implementation of prov-o in the datamodel.
Currently this is how all the provenance record look like.
```
{
  "_id": "20.5000.1025/MKA-93P-4MS/40",
  "id": "470d7761-7053-4c08-856e-f7d68ad9c449",
  "eventType": "update",
  "agent": "processing-service",
  "subject": "20.5000.1025/MKA-93P-4MS",
  "subjectType": "DigitalSpecimen",
  "timestamp": "2023-02-24T11:22:33.96339360Z",
  "eventRecord": {
    "id": "20.5000.1025/MKA-93P-4MS",
    "midsLevel": 0,
    "version": 40,
    "created": 1677237753.9051137,
    "digitalSpecimen": {
      "ods:physicalSpecimenId": "dissco-futures",
      "ods:type": "BotanySpecimen",
      "ods:attributes": {
        "ods:physicalSpecimenIdType": "cetaf",
        "ods:organizationId": "https://ror.org/0349vqz63",
        "ods:specimenName": "dissco-futures",
        "ods:datasetId": "A Dataset-40",
        "ods:physicalSpecimenCollection": "A collection",
        "ods:sourceSystemId": "20.5000.1025/GW0-TYL-YRU",
        "dwca:id": "dissco-futures"
      },
      "ods:originalAttributes": {
        "dwc:eventDate": "1994-08-25",
        "dwc:family": "Cupressaceae",
        "dwc:genus": "Glyptostrobus",
        "dwc:higherGeography": "Indo-China",
        "dwc:specificEpithet": "pensilis",
        "dwc:nomenclaturalCode": "ICBN",
        "dwc:catalogNumber": "00622948",
        "dwc:country": "LA",
        "dwc:basisOfRecord": "PreservedSpecimen"
      }
    }
  },
  "change": [
    {
      "op": "replace",
      "path": "/ods:attributes/ods:datasetId",
      "value": "A Dataset-40"
    }
  ],
  "comment": "Specimen has been updated"
}
```

I think it has all the information that we need:
- prov:Entity -> We got both the PID (`subject`) as well as the full state after the update `eventRecord`
- prov:Activity -> We got the change that has been made `change`
- prov:Agent -> This is `agent` (will make a change so this reflect the user or source system instead of the processing service or can the processing service be the `prov:wasGeneratedBy`?) 
- prov:generatedAtTime or prov:atTime -> `timestamp`

Can someone help with the mapping and indicate if we miss any information in the provenance record.
Currently these records are generated for the creation and each addional change of DigitalSpecimen, DigitalMediaObject and Annotation objects.

**Comment by jgrieb** [comment]
So is the value within `"eventRecord"` a complete snapshot of the DS at that specific time instant (after the change, but before any new change occure)?

Comparing this example to PROV-O, here it feels like a mesh-up between the `prov:Entity` and the `prov:Activitiy`, and the relation between both (`prov:wasGeneratedBy`) is only implicitly represented. Also in PROV-O we would like to explicitly express the relation to previous versions of the DS (an update means *isRevisionOf* a previous version). I guess this is also implicitly given, here in this case it would be `20.5000.1025/MKA-93P-4MS/40`.

So, what exactly do we want to achieve? Should the data structure itself be modeled closer to the PROV-O data model, or do we just want to check if it's possible to map our data structure to PROV-O (meaning a more explicit expression of the semantics, which are currently implicitly encoded in your example)?
