### ISSUE TITLE
physical specimen identifiers in Digital Specimen PID Kernel

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/openDS#36]
**Need:** 
All identifiers representing a specimen should be in the PID Kernel to enable machines to find relationships between data that include one of these identifiers.
There should be a **one-to-one relation** between the physical specimen (or sometimes: locally stored digital specimen object) and DiSSCo digital specimen. This can be established by having an identifier for the physical specimen in the digital specimen pid record that is locally unique in the providing organisation.
One physical specimen id should be marked as **primary**, that is the one that should be **locally unique** and will be shown in a limited overview of the specimen.

**Assumptions:**
All physical specimen objects have an id that (if possible) is **physically attached to the specimen object,** as e.g. barcode, written or printed id on a label or digital on a chip. Likewise if a locally stored object is digital and treated as a specimen (e.g. a digital sound recording), it is assumed that it has an specimen id attached to it. In all cases this is called a physical specimen id in DiSSCo (derived from MIDs).
Specimens may have more than one id and these are not always unique. These may be old identifiers that cannot be made unique anymore.
All physical specimen objects have at least one id that is locally unique within the providing organisation or within a certain collection or system in that organisation. If this is not the case, an organisation is required to change this when connecting with DiSSCo, as otherwise uniqueness of digital specimen IDs could not be ensured and reliable data linking between DSArch and a local system could not be established.
Local staff can find a local object with the unique id and knowing the type of the identifier
To know the type of the identifier the providing organisation uses a particular pattern in the identifier string and/or has a name for the identifier (for example catalog number, tissue id, regid).
each providing organisation has a unique identifier (ROR or Wikidata Q number)

Options to make a physical specimen id unique when it is not globally unique and not unique with an organisation:

ROR/Qnumber + collection id + physical identifier
problem: the collection may use two different catalogs each with a different identifier, for example one catalog for preserved fishes and one catalog for fish tissues.

ROR/Qnumber + system id + physical identifier
problem: there may be multiple types of identifiers stored in one system, e.g. an old and new one.

ROR/Qnumber + identifier name/type + physical identifier (**preferred option**)
This seems reliable assuming that a providing organisation is able to distinguish multiple identifier types with different (unique) names within the organisation.

**Design choices:**
if a physical identifier is globally unique, ROR/Qnumber and identifier name would not be needed, if it is locally unique, a ROR would be needed but not an identifier name. To keep it simple though we could **always capture these three elements for a physical identifier.** That avoids mistakes by dataproviders and having to make a choice when providing data.
The ROR/Qnumber for the primary physical specimen ID should be always the one from the current providing organisation. e.g. if an object moves from organisation A to organisation B, the ROR will be from organisation B even if the identifier from organisation A is kept. We assume that there is always one providing organisation, if there is more than one, then we should capture the primary responsible one. Therefore we only need to store one PID for the hosting organisation.
specimen IDs from organisations that do not provide physical access to the specimen should **not** be included as physical specimen id, e.g.identifiers for a GBIF or ENA specimen record.
identifier name/type may be of a certain language (or not) and there may be multiple in use in a providing organisation for the same identifier, but we will store only one and assume there is no need to store the language of the name/type.

**DOI Kernel metadata requirements and preferences**

primaryReferentType will be a creation (the digital specimen is the referent, not the physical object) A digital specimen refers to more than only the physical specimen and includes data related to the specimen. Therefore a physical specimen identifier does not seem to be a referentIdentifer.

DOI schema recognises several types of identifiers:
for physical specimen identifiers we can use some fields in the DOI schema that are also used for creations and parties:
For the type a subset of values can be used from creationIdentifier: ProprietaryIdentifier if the identifier is custom made by the organisation, URN, UUID. Others do not seem relevant except URI and DOI, but rather than have values for DOI, Handle, CETAF Stable ID, IGSN, ARK, PURL, it is probably sufficient for a machine to just use the type URL for them. For DOIs there are two other possible elements:  returnType (The (primary?) type of content that is returned by the URI) and  doesContentNegotiation. These two may be relevant for any URL though.

userDefinedType can be used as a string for the name/type. We could leave out validNameSpace and governingParty as this seems not very relevant for our purpose.

to summarise:
primaryReferentType = "creation"
referentType = "digital specimen"
structuralType = digital

referentDoiName = "10.22/2FA-HGB-4Y3" (for example)
referentName = (use name of the physical object in the collection), not mandatory 
kernelInformationProfile = "21…")

**primaryPhysicalSpecimenId
    id= "rnhz.zoo.123"
    idType = (one of: ProprietaryIdentifier, UUID, URN, URL)
    idUserDefinedType = "cat nr", **max. 30 characters**. (examples: "crs catalog number", "registratienr", "cetaf stable id") 
    returnType (optional, e.g. "text/html" or "application/json"
    doesContentNegotiation (optional)
    reasonForAbsenceOfPhysicalSpecimen (required if no physicalspecimenid is given, text **max. 255 characters**

otherPhysicalSpecimenIDs (sequence, optional)**

if primarySpecimenID and reasonForAbsenceOfPhysicalSpecimen are both filled then the record is invalid and should not validate.

**Comment by dagendresen** [comment]
I appreciate the work initiated on designing a physical specimen ID. But I am worried about the design choice to intermix locally unique and globally unique specimen identifiers. And urge to keep these two things separate.

ROR/QID - should this in some way always remain the ID for the institution holding the specimen when the physical specimen ID was created? Or potentially be updated to the ID for the institution currently holding the specimen? Thus making the physical specimen identifier string actually subject to change through time...!!

The recommended best practice must be for the physical specimen identifier to be globally unique.

**Comment by wouteraddink** [comment]
Hi Dag,
Yes the idea is to keep locally and globally unique id's separate, into 3
different categories: id's that are urls (globally unique and resolvable),
id's that are globally unique and not urls (guids, urns)  and id's that are
locally unique.

The goal is to have a 1:1 relation between physical and digital specimen,
there should be only one ds for a physical specimen. Another goal is to
keep changes in existing collections to a minimum, so we have to deal with
the current situafion that physical specimen id's that are not globally
unique and change over time.

There will also be situations where id's are not even locally unique, in
that case we cannot reliably create ds for the objects so then there is a
local change in the collection still needed.

Since the ds will have pids, it is not required that the physical specimen
also have pids but it would still be recommended best practice.

Kind regards,
Wouter

Op di 7 mrt. 2023 06:51 schreef Dag Endresen ***@***.***>:

**Comment by jbstatgen** [comment]
@wouteraddink The approach that you are proposing for creating physical specimen IDs if they are not globally (and locally) unique seems supported by Latimer Core's approach to its `ltc:Identifier` class (https://github.com/tdwg/cd/labels/Class%3AIdentifier). 

> ROR/Qnumber + identifier name/type + physical identifier (preferred option)

ltc:Identifier has three properties that map to the above components of the proposed process for creating a globally unique ID for the physical specimen:

* `ltc:identifierSource`: ROR/Qnumber
* `ltc:identifierType`: identifier name/type
* `ltc:identifierValue`: physical identifier

While Latimer Core focuses on the collection-level, its identifier scheme should and seems to work well at the specimen-level.

**Comment by wouteraddink** [comment]
Thanks Jutta,
Good to know!

Op za 18 mrt. 2023 15:08 schreef jbstatgen ***@***.***>:

**Comment by sharifX** [comment]
We have moved the discussion in the [Digital Specimen RFC](https://docs.google.com/document/d/1hj5M9Cko5LduDv1H8CUYdGocg_B3YUf6MafoZPHPaec/edit#heading=h.ksv53ki6luu8) for the FDO Record. We have decided to use the term "primarySpecimenObjectId" and "normalisedSpecimenObjectId". 

From the RFC: 

> _primarySpecimenObjectId
> Primary local identifier used to identify the physical specimen, which is a preserved material entity. This identifier is usually physically attached to the specimen, e.g. as barcode. It is recommended to use a global and resolvable identifier if available. The host of the physical specimen should be able to find the physical specimen with only this ID plus, if that is not globally unique, the primarySpecimenObjectIdName._

and 

> 
> normalisedSpecimenObjectId
> For internal processing purposes only to make a local identifier globally unique. This is the primarySpecimenObjectId if it is globally unique or a combination of ROR ID string, source system ID string, primarySpecimenObjectId if it is a proprietary identifier.
