### ISSUE TITLE
where is the ods ontology? 

### ISSUE THREAD

**Issue by smrgeoinfo** [DiSSCo/openDS#41]
there's nothing in the https://github.com/DiSSCo/openDS/tree/master/ods-ontology folder in the repository.   What is the target of the harmonization work in the https://github.com/DiSSCo/openDS/tree/master/harmonisation folder.

I'd like to be able to compare the OpenDS model with our work on sample description in the iSamples project. Our schema is documented at https://isamplesorg.github.io/metadata/, json schema at https://github.com/isamplesorg/metadata/blob/main/src/schemas/iSamplesSchemaCore1.0.json

**Comment by smrgeoinfo** [comment]
Thanks!  Since our objectives are pretty similar it seems, I hope we can keep the iSamples and OpenDS samples aligned.  I'll keep an eye out for an OpenDS model.

**Comment by sharifX** [comment]
@smrgeoinfo we have done some clean up in the opends repo. the current state is now reflected. Please look at the README file and the model folder. The ontology folder has been removed. Our focus now is on the specification side and a path towards a MVP implementation (see https://sandbox.dissco.tech/). We try to use existing ontology and vocabularies whenever possible. While we have introduced a few new terms, this does not currently require a new ontology.
