### ISSUE TITLE
geological timescale ontology

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/openDS#6]
There is an ontology for the geological timescale here https://github.com/CGI-IUGS/timescale-ont and a dataset representing the international chronostratigraphic chart nearby https://github.com/CGI-IUGS/timescale-data
The International Commission on Stratigraphy are planning to adopt this as the point-of-truth for the standard geological timescale.

related also: proposed Darwin Core Vocabulary Enhancement - ChronometricAge: https://github.com/tdwg/chrono/issues/15

**Comment by nicholascar** [comment]
Just confirming that indeed the International Commission on Stratigraphy are indeed planning on adopting this Geo Time Scale dataset and, in future, producing all Charts from it as automated reports.

This will take a while but we should get an English-only chart generated in the first quarter of 2021. Regards Nick (who is now Webmaster of the ICS)

**Comment by smrgeoinfo** [comment]
[tdwg/chrono](https://tdwg.github.io/chrono/terms/) is targeted for reporting numeric temporal coordinate locations; the Geologic time scale reports ages using time ordinal eras-- named intervals anchored in the rock record via GSSP.  The numeric temporal coordinates of the boundaries of those intervals are updated as new data become available.

**Comment by sharifX** [comment]
we have incorporated Chronometric age in our new data model (see: https://github.com/DiSSCo/openDS/blob/master/data-model/fdo-type/digital-specimen/0.3.0/schema/chronometric-age.json)
