### ISSUE TITLE
Concrete implementations would help to develop data model agilely

### ISSUE THREAD

**Issue by esko-piirainen** [DiSSCo/openDS#7]
Thanks for your hard work creating this openDS datamodel! The documentation looks suberb.

We (Luomus) will be commenting the model soon here via issues especially from point of view of transactions (because that is the first concrete implementation needed as part of Elvis) and annotations (because this interests us a lot and there would be great demand for ability to share annotations between institutions). 

This comment is from a more general point of view regarding how a data model / standard can and should be created so that it will actually "pick-up": will have concrete implementations and wide usage in the future.  

I strongly believe, that concrete implementations and data model development should go hand in hand. This can also be called 'agile development'. Data modelling can be done from purely academic point of view, but if you lock it before any real implementations, it may not actually suit all needs. It is very difficult to be able to think about all possible scenarios without actually implementing stuff.

So we would recommend and encourage to create concrete pilot interfaces that solve **concrete use cases** (**things that provide value to actual real life users**) as part of specifying the data model. We are happy to create prototypes for example for Elvis loans, annotation sharing and dataset metadata search engine (if part of openDS).

Esko Piirainen
The Finnish Biodiversity Information Facility (FinBIF)
Finnish Museum of Natural History LUOMUS

**Comment by hardistyar** [comment]
Thank you for your words of support. I agree with you 100% about how the process should proceed as a kind of 'spiral' moving forward - based on use cases, specification informing implementation and use which in turn again informs further specification. I would be very happy when you try to implement something and discover and report the problems. Thus far, the work has focussed on establishing the skeleton but then we get more real.

Please look also at the [use cases](https://github.com/DiSSCo/openDS/blob/master/Use-cases.md) and add missing ones and/or ones that interest you.
