### ISSUE TITLE
User stories / use caes as part of model planning

### ISSUE THREAD

**Issue by esko-piirainen** [DiSSCo/openDS#8]
I take a look at https://github.com/DiSSCo/openDS/blob/master/Use-cases.md 

The use cases are written in a format that makes it more like a list of _functional requirements_.

There could be real benefit of having also use cases that are formatted from the point of view of a real user.

For example I randomly picked one:

> Use case S4: Linking information from/to other (sub-)disciplines
> 
> Linking information makes taxonomic work easier and enables linkage of data and information from and to other disciplines. Community curation saves a lot of effort in making these links compared to the case where every collection must make all the (semantic) links on their own.

Well, I'm not entirely sure what this means. The benefit of a user story is that it is quite easy to understand for anyone (end user, developer, funder, etc). The case S4 probably covers a wide range of user stories, but one could for example be something like this:

> As a researcher studying change of species distribution over time in a certain country, I would like to be able to access specimen by country identifier, so I don't have to download all potential specimen all and try to interpret countries from verbatim locality descriptions.

And actually that is not a good use case because it implies a technical solution to the problem. Maybe interpreted coordinates would be a better solution? So the use case could be generalized even more:

> As a researcher studying change of species distribution over time in a certain country, I would like to be able to access specimen easily by location

**Comment by sharifX** [comment]
Hi @esko-piirainen, 

Thanks for your comment. Yes, indeed user stories are helpful to figure out the specific role, results, and benefits. We have been collecting and using [user stories](https://github.com/DiSSCo/user-stories/issues) for the past year or so. I think it will be useful to carefully look at the ones we have and see how we can group them under the openDS use cases. As we advance, we will be using both user stories and use cases and also possibly story mapping activities. 

For now, I have identified a few existing user stories and created a label for openDS: https://github.com/DiSSCo/user-stories/labels/openDS.

The one you identified is probably captured via this one: https://github.com/DiSSCo/user-stories/issues/264 (if not feel free to create a new one [here](https://github.com/DiSSCo/user-stories/issues).

**Comment by sharifX** [comment]
suggesting to use user-stories github repo for creating new ones.
